### ISSUE TITLE
pip install cufinufft throws: No such file or directory: 'python/cufinufft/requirements.txt'

### ISSUE THREAD

**Issue by dimitsev** [flatironinstitute/cufinufft#146]
System: Ubuntu 22.04.2 LTS
Python version: 3.10.9 (via `sudo apt install python3`)
Nvidia driver version: 510.108.03 (via `sudo apt install nvidia-driver-510`)
CUDA version: 11.6 (via `sudo apt install nvidia-cuda-toolkit`)
GPU: Nvidia RTX A5000

`pip install cufinufft` throws: `No such file or directory: 'python/cufinufft/requirements.txt'`

In detail:

```
Collecting cufinufft
  Downloading cufinufft-1.1.tar.gz (8.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-aqi2n6gm/cufinufft_7137ea3d29d64fdbb7ce833433127ef5/setup.py", line 9, in <module>
          with open(os.path.join('python/cufinufft', 'requirements.txt'), 'r') as fh:
      FileNotFoundError: [Errno 2] No such file or directory: 'python/cufinufft/requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by roflmaostc** [comment]
Can confirm, encountered the same.

**Comment by dimitsev** [comment]
`pip install cufinufft` works on python 3.8.X (where X is whatever). I tested it on Ubuntu 20.04 LTS. However, I am not sure if it works on Windows 10/11. Our people discovered https://github.com/jyhmiinlin/pynufft and https://cupy.dev/ as alternatives to cuFINUFFT and to our custom CUDA kernels that we wrote using pycuda.

**Comment by janden** [comment]
Able to confirm as well.

So what's happening here is:

- We don't have binary wheels published for py310 (only up to py39).
- Because of this, `pip` tries to find a source distribution to compile.
- Looks like we forgot to (or decided not to) upload a source distribution for v1.2.
- So `pip` finds the latest source distribution, which is v1.1.
- This version had a bug in the published package where certain files were missing from the manifest (in particular the file you're describing in `python/cufinufft/requirements.txt`).

I'm going to publish some wheels for py310 and see whether we can get a source distribution up for v1.2.

**Comment by janden** [comment]
So v1.2 now has a py310 wheel uploaded. Installed and checked that everything works under `numpy==1.23.0` and `pycuda==2021.1`.
