### ISSUE TITLE
TIME flag not consistently treated in tests

### ISSUE THREAD

**Issue by janden** [flatironinstitute/cufinufft#19]
Even with the flag turned off, these codes output certain timings. Since these are only there for testing purposes, it might make sens for them to ignore the TIME flag altogether.

**Comment by garrettwrong** [comment]
I noticed this when I ran the example test, but it looked like the methods ASPIRE was calling were silent, so I assumed it was just intentionally there for the examples (which seemed fine).  Did you get output somewhere you thought it definitely shouldn't be or is this just for consistency?

I ask because if we're leaking, it can blow up logs in ASPIRE pretty quick 😅 .

**Comment by janden** [comment]
> it looked like the methods ASPIRE was calling were silent

Yes that seems good. The timing scripts are using the TIME flag to determine whether to output their own timing (wrapping the library calls). This is just for consistency. When it's disabled, some parts are timed while others aren't. It would be simpler for them to always output timings, since they're essentially timing code.s

**Comment by MelodyShih** [comment]
The places TIME flag are used in the test codes are around a call of cudaMalloc(&a,1), which is now redundant. I was using it to "warm up" GPU but since we exclude the time allocating the GPU memory, it is no longer needed. I will delete those codes and create a pull request.
