### ISSUE TITLE
Consider Breaking CUB Dependence

### ISSUE THREAD

**Issue by garrettwrong** [flatironinstitute/cufinufft#2]
It is nicer when code stands alone.  I would like to look at how much work it would be to either include a minimal part of CUB (frozen, and with citation), or roll our own similar function(s).  This would be better than a submodule or external dep.

From our 5/12 discussion, I got the impression this is not too much work.  I will look into it at a good time.

**Comment by MelodyShih** [comment]
hi Garret, here are some information that might save you some time -- the library is used for exclusive and inclusive scan operation on arrays in file `spread2d_wrapper.cu` and `spread3d_wrapper.cu`. One can use thrust which is a library from NVIDIA and it's in cuda toolkit. I had an impression that CUB has a better performance so I changed to use it instead. There is another place using CUB (`spreadinterp2d.cu` for Paul's method). I used it for a reduction inside threadblocks but since the method is not really used now, we probably don't have to worry about it. 

Here is a link to CUB's documentation: https://nvlabs.github.io/cub. It is a C++ header library so it doesn't need to be installed separately. I actually won't worry too much about this dependency but maybe it is still nice to have the code standing alone.

**Comment by garrettwrong** [comment]
Cool, thanks.  Yes CUB looks very useful and I can see why you wanted to use it for development.  While I had no major problem building and running the code, the easier we make it on users the more likely they will have success (and less time doing support).  Particularly I am thinking about the target users of ASPIRE, where this would be a tertiary dependence in their tree.

These are probably better than thrust.  I'll try to look more tomorrow.

**Comment by janden** [comment]
> the easier we make it on users the more likely they will have success (and less time doing support)

Yeah I think this makes sense. Especially if it's header-only, it's quite trivial to include (no extra build instructions) and we're not sacrificing too much by freezing the current version.

> These are probably better than thrust.

Might be good to have some speed comparisons between CUB and thrust here before we get too bogged down. @MelodyShih did you have some benchmark code for this?

**Comment by MelodyShih** [comment]
I don't have codes written specifically for testing the performance for the two libraries. I tested them within cufinufft but didn't remain the thrust codes unfortunately. It won't be hard to write some codes to test the performance. I can do that if it is helpful.

**Comment by janden** [comment]
> I can do that if it is helpful.

If you have time and it's not too complicated. If the built-in (?) thrust is sufficient, we could eliminate CUB as a dependency, which would simplify things a little bit.

**Comment by ahbarnett** [comment]
It seems like both thrust and CUB are actively NVidia-supported, and serve different roles:
https://developer.nvidia.com/gtc/2020/video/cwe21285

Melody, if you don't have time to do this comparison - feel no pressure unless it's a useful part of your GPU professional development - we could bring Libin in to help.

But what was wrong with the idea of bundling CUB headers in this repo, and listing a range of CUDA versions that work with it?

**Comment by garrettwrong** [comment]
I think the submodule is reasonable (it only has the clone line diff from a common install procedure).  I was only hoping to reduce the manual steps to install and build correctly, and I think the submodule does that.  CUB could also be hard included if that is preferred. Same effect.

In my eyes #1 covered this enough, and it could be closed if there are no strong feelings about it.

**Comment by MelodyShih** [comment]
Alex, thanks for sharing the video. They also mentioned that CUB will be in the cuda toolkit in the next release of cuda. 
I can do the comparison. No problem with that. :)

**Comment by MelodyShih** [comment]
Here are some performance results using this [code](https://github.com/MelodyShih/cuFINUFFT-bench/blob/master/others/thrust_vs_cub.cu) on a NVIDIA V100 card -- 

|    N   |    10    |    100   |   1000   | 10000    | 100000
|:------:|:--------:|:--------:|:--------:|----------:|--------|
| Thrust | 2.55e-05 (sec) | 2.58e-05 | 2.56e-05 | 2.65e-05 | 2.76e-05 |
|   CUB  | 1.45e-05 | 1.43e-05 | 1.48e-05 | 1.43e-05 | 1.48e-05 |

N is the size of the array to do exclusive sum and the time is recorded in seconds. Noticing that the runtime is short comparing to the whole nufft process (the cufft plan takes about 0.19 sec), maybe we don't have to take into account of the performance perspective of the two libraries.(Sorry for bringing the performance issue up earlier)

**Comment by ahbarnett** [comment]
I'm confused why the time doesn't scale like N? 1e10 flops I can believe, but if you increase N to 1e6, 1e7, is it still 1e-5 sec?  In cuFinufft context is this going to affect some inner loop of the spreading/interpolation, ie, something critical?

**Comment by MelodyShih** [comment]
|    N   |    1e1 ~ 1e5 | 1e6 | 1e7 | 1e8 | 1e9 |
|:------:|:--------|:-------:|:-------:|:----------:|:-----:|
| Thrust | ~ 2.55e-05 (sec) | 0.000328 | 0.000432 | 0.00149 | 0.0111 |
|   CUB  | ~ 1.45e-05  | 1.96e-05 | 0.000113 | 0.00104 | 0.0102 |  

I added more data point into the table. I guess it is because the N I tested are small and some constant cost of the code dominants the timing. 

The function is called when setting up the subproblem properties so it's outside the inner loop of the spreading/interpolation. If one has different data with same location of nonuniform points, the call only happens once.

**Comment by ahbarnett** [comment]
Thanks, Melody! It indicates 1e11 elements/sec, for both libraries, plus around 20 microseconds start-up cost.
If this is outside an inner loop, my intuition is that the difference can't matter for speed - if you agree, and it's not hard to switch to thrust while making installation/dependencies easier - I suggest go ahead - but it should be a joint decision w/ others.

Meanwhile I've nearly rewritten the finufft.cpp guru inner algorithm. Thanks for your early work on 2dmany, which continues to help me. I found it weird that there is no OMP command to query the number of threads that *will* be used in the next parallel block (had to write my own function for this). Cheers, Alex

**Comment by janden** [comment]
Yes thank you for running these tests. I think we can afford the (slight) performance drop by switching to the built-in thrust library, in that case. One less thing to worry about.

**Comment by MelodyShih** [comment]
Sure, we can change to use thrust. I am not sure about if there is similar functionality under thrust that can do a scan on an array inside a cuda kernel -- I will look into it.

Alex, glad to hear that it helps:) I guess maybe the execution might in potential dynamic enough such that the prediction of number of threads can be hard. Looking forward to see the final guru interface!
