### ISSUE TITLE
Naming and setting `ntransfcufftplan`

### ISSUE THREAD

**Issue by janden** [flatironinstitute/cufinufft#8]
I find this name a little confusing. After digging through the source code, it appears to be the “block size” of the algorithm, that is, the number of inputs to process simultaneously (which, is therefore equal to the number of inputs in the CUFFT plan).

Maybe something like `block_size` would be better? Or `ntransfblock`? We should also discuss good rules of thumb for setting this by default since most users won't want to deal with it. In the tests, we default to 8, but I saw much better performance on my laptop for 16 and 32, after which it seems to saturate.

**Comment by ahbarnett** [comment]
In my new guru finufft interface I call this maxblocksize.
If it is positive, then, internally, blocksize = min(ntransf, maxblocksize)
or if this is 0 a default internal choice of blocksize is used based on #threads OMP sees:

https://github.com/flatironinstitute/finufft/blob/7403bab59be7ac4e3806d9a9c349faefa10dc7b7/src/finufft.cpp#L127

Not sure of the right blocksize for GPU.
Suggest similar names, though,  Alex

**Comment by MelodyShih** [comment]
I am thinking this is a variable to determine how many data we want to apply FFT at one call of cufftExec so that we can take advantage of the performance from "cuFFTmany". This is why I named it like this. We still spread data one by one, which is different from finufft having threads spreading multiple data at a time. But I agree that the name can be confusing. Using maxblocksize (it seems that maxbatchsize is used in the link?) sounds good to me.

Regarding the default value of it, I don't have an immediate answer. More experiments are needed for a better rule of thumb -- I would imagine this decision will depend largely on how cuFFT performs and this can vary with the size of the transformation per data. I can try to collect some data these two days and we'll then probably have better idea about how to set it.

**Comment by ahbarnett** [comment]
Yeah, I meant maxbatchsize.
Don't worry too much about optimal value. My default was # omp threads. Whatever the GPU equiv is (# SM's?). The important thing is to stabilize the interface and allow opts to be controlled. Benchmarking will be an ongoing team effort.

**Comment by janden** [comment]
> Using maxblocksize (it seems that maxbatchsize is used in the link?) sounds good to me.

Good. Let's make it `maxbatchsize` then for compatibility with Finufft.

> Regarding the default value of it, I don't have an immediate answer.

Yeah we can leave it at `maxbatchsize=8` for now, that's fine with me. Like I said, it looked like (on my laptop) that it saturates after a while, so it may be enough to pick it “large enough” to get decent performance without taking up too much memory. I will make a separate issue about this.
