### ISSUE TITLE
Inaccurate type 1 transform in Python

### ISSUE THREAD

**Issue by janden** [flatironinstitute/cufinufft#85]
When running the type 1 transform in Python with a small number of nonuniform points, the output seems to be garbage (i.e., order one error). Sometimes it's zero, sometimes not. Initializing the output array with a fixed value shows that something the array is being written to. I've not been able to reproduce this in the C interface, so it's likely this has something to do with the Python binding.

```
import numpy as np
import pycuda.autoinit
from pycuda.gpuarray import GPUArray, to_gpu
from cufinufft import cufinufft

N1, N2 = 256, 256
M = 10
dtype = np.float32
complex_dtype = np.complex64

kx = np.random.uniform(-np.pi, np.pi, size=M)
ky = np.random.uniform(-np.pi, np.pi, size=M)

c = (np.random.standard_normal(M)
     + 1j * np.random.standard_normal(M))

kx = kx.astype(dtype)
ky = ky.astype(dtype)
c = c.astype(complex_dtype)

fk_gpu = to_gpu(np.full(fill_value=-123, shape=(N1, N2),
    dtype=complex_dtype))

plan = cufinufft(1, (N1, N2), dtype=dtype)
plan.set_pts(to_gpu(kx), to_gpu(ky))

plan.execute(to_gpu(c), fk_gpu)

fk = fk_gpu.get()

nt1 = int(0.37 * N1)
nt2 = int(0.26 * N2)

x, y = nt1 - N1 // 2, nt2 - N2 // 2
fk_true = np.sum(c * np.exp(1j * (x * kx + y * ky)))

print(f"fk={fk[nt1, nt2]}, fk_true={fk_true}")

err = np.abs(fk[nt1, nt2] - fk_true)
rel_err = err / np.max(np.abs(fk))

print(f"err={err}, rel_err={rel_err}")
```

**Comment by MelodyShih** [comment]
I found that the error is caused by this line ```plan.set_pts(to_gpu(kx), to_gpu(ky))```. 
The `GPUArray`s return by `to_gpu(kx)`, `to_gpu(ky)` seem to be freed earlier than we want.

Changing the related lines as follows fixes the error. 
```
kx_gpu = to_gpu(kx)
ky_gpu = to_gpu(ky)
c_gpu = to_gpu(c)

plan = cufinufft(1, (N1, N2), dtype=dtype)
plan.set_pts(kx_gpu, ky_gpu)
```

I am not sure why there is no problem of running the example codes `example2d1many.py` and `example2d2many.py`. But it seems that it is not from the small M we used here, e.g. changing n_transf from 2 to 1 also gives order 1 error. 

I will create a pull request to update the example codes.
